export type ServiceCategory =
  | 'personal'
  | 'academic'
  | 'business'
  | 'schemes-central'
  | 'schemes-bihar';

export type IconColor = 'blue' | 'orange' | 'green' | 'purple' | 'rose';

export interface Service {
  id: number;
  cat: ServiceCategory;
  name: string;
  sub: string;
  icon: string;
  color: IconColor;
  time: string;
  fee: string;
  tatkal: boolean;
  popular: boolean;
  docs: string[];
  desc: string;
  steps?: string[];
}

export const services: Service[] = [
  // ── PERSONAL DOCUMENTS (32) ──────────────────────────────────────────────
  { id: 1,  cat: 'personal', name: 'Caste Certificate', sub: 'SC/ST/OBC/EBC/BC', icon: 'shield', color: 'blue', time: '1–2 Days', fee: '₹299', tatkal: true,  popular: true,  docs: ['Aadhaar Card', 'Ration Card', "Father's Caste Proof", 'Passport Photo'], desc: 'Official caste certificate from SDO/CO office for reservation benefits in jobs and admissions across Bihar.' },
  { id: 2,  cat: 'personal', name: 'Income Certificate', sub: 'Annual Income Proof', icon: 'indian-rupee', color: 'orange', time: 'Same Day', fee: '₹249', tatkal: true,  popular: true,  docs: ['Aadhaar Card', 'Ration Card', 'Salary Slip / Self Declaration', 'Passport Photo'], desc: 'Income certificate from SDO/CO for scholarship, scheme eligibility and admission purposes.' },
  { id: 3,  cat: 'personal', name: 'Residence Certificate', sub: 'Nivas Praman Patra', icon: 'home', color: 'blue', time: 'Same Day', fee: '₹249', tatkal: true,  popular: true,  docs: ['Aadhaar Card', 'Ration Card / Voter ID', 'Electricity Bill', 'Passport Photo'], desc: 'Residence certificate confirming permanent address in Bihar. Normal and Tatkal both available.' },
  { id: 4,  cat: 'personal', name: 'Domicile Certificate', sub: 'State Domicile Proof', icon: 'map-pin', color: 'green', time: '1–2 Days', fee: '₹299', tatkal: false, popular: false, docs: ['Aadhaar Card', 'Birth Certificate', 'Residence Proof', 'Passport Photo'], desc: 'Bihar domicile certificate for state quota reservations in government jobs and admissions.' },
  { id: 5,  cat: 'personal', name: 'EWS Certificate', sub: 'Economically Weaker Section', icon: 'users', color: 'purple', time: '1–2 Days', fee: '₹349', tatkal: true,  popular: true,  docs: ['Aadhaar Card', 'Income Proof', 'Property Details', 'Passport Photo'], desc: 'EWS certificate for 10% reservation in central government jobs and educational institutions.' },
  { id: 6,  cat: 'personal', name: 'NCL Certificate', sub: 'Non-Creamy Layer', icon: 'badge-check', color: 'blue', time: '1–2 Days', fee: '₹349', tatkal: true,  popular: false, docs: ['Aadhaar Card', 'Caste Certificate', 'Income Proof', "Parents' Service Records"], desc: 'Non-Creamy Layer certificate for OBC candidates to avail reservation benefits in central services.' },
  { id: 7,  cat: 'personal', name: 'Birth Certificate', sub: 'Normal + Delayed', icon: 'baby', color: 'orange', time: 'Same Day', fee: '₹199', tatkal: true,  popular: true,  docs: ['Hospital Discharge Summary', "Parents' Aadhaar", 'Marriage Certificate'], desc: 'Official birth certificate from municipality or panchayat. Delayed registration (1 year+) also available.' },
  { id: 8,  cat: 'personal', name: 'Death Certificate', sub: 'Normal + Delayed', icon: 'file-minus', color: 'blue', time: 'Same Day', fee: '₹199', tatkal: false, popular: false, docs: ['Hospital Death Report', "Deceased's Aadhaar", "Applicant's Aadhaar"], desc: 'Death certificate for legal, property and insurance matters. Delayed registration also assisted.' },
  { id: 9,  cat: 'personal', name: 'Character Certificate', sub: 'Police Verification', icon: 'shield-check', color: 'green', time: '7–10 days', fee: '₹399', tatkal: false, popular: false, docs: ['Aadhaar Card', 'Passport Photo', 'Address Proof', 'Purpose Letter'], desc: 'Character and conduct certificate from local police station or SDO office for various purposes.' },
  { id: 10, cat: 'personal', name: 'Land Possession Certificate', sub: 'LPC', icon: 'land-plot', color: 'orange', time: '2–3 Days', fee: '₹499', tatkal: false, popular: false, docs: ['Aadhaar', 'Khasra Khatauni', 'Jamabandi', 'Application Form'], desc: 'LPC issued by Circle Officer confirming land ownership and possession in Bihar.' },
  { id: 11, cat: 'personal', name: 'Marriage Certificate', sub: 'Registration', icon: 'heart', color: 'purple', time: '1–2 Days', fee: '₹399', tatkal: false, popular: false, docs: ['Both Aadhaar', 'Wedding Photos', 'Witness Aadhaar', 'Marriage Invitation Card'], desc: 'Official marriage registration certificate from municipality or registrar office.' },
  { id: 12, cat: 'personal', name: 'Disability Certificate', sub: 'Divyang Certificate', icon: 'accessibility', color: 'blue', time: '10–15 days', fee: '₹299', tatkal: false, popular: false, docs: ['Aadhaar', 'Medical Reports', 'Passport Photo', 'Hospital Certificate'], desc: 'Disability certificate from SDMCH or Government Hospital for Divyang pension and scheme benefits.' },
  { id: 13, cat: 'personal', name: 'Senior Citizen Card', sub: '60+ Age Proof', icon: 'user-check', color: 'green', time: '1–2 Days', fee: '₹199', tatkal: false, popular: false, docs: ['Aadhaar Card', 'Age Proof', 'Passport Photo'], desc: 'Senior citizen card for concessions in transport, hospitals and government schemes.' },
  { id: 14, cat: 'personal', name: 'Ration Card', sub: 'New / Correction / Transfer', icon: 'shopping-basket', color: 'orange', time: '3–5 Days', fee: '₹499', tatkal: false, popular: true,  docs: ['Aadhaar (All Members)', 'Income Proof', 'Address Proof', 'Family Photo'], desc: 'New ration card or correction in existing card under NFSA for subsidized food grains.' },
  { id: 15, cat: 'personal', name: 'Aadhaar Services', sub: 'Enrollment / Update / Print', icon: 'fingerprint', color: 'blue', time: '1–3 days', fee: '₹149', tatkal: false, popular: true,  docs: ['Original ID Proof', 'Address Proof', 'Mobile Number'], desc: 'Aadhaar new enrollment, address/mobile/name update, biometric update and reprint assistance.' },
  { id: 16, cat: 'personal', name: 'PAN Card', sub: 'New + Correction', icon: 'credit-card', color: 'purple', time: '10–15 days', fee: '₹399', tatkal: false, popular: true,  docs: ['Aadhaar Card', 'Passport Photo', 'Signature', 'Address Proof'], desc: 'PAN card new application or correction for income tax, banking and financial transactions.' },
  { id: 17, cat: 'personal', name: 'Voter ID', sub: 'New / Correction / Duplicate', icon: 'vote', color: 'green', time: '3–5 Days', fee: '₹299', tatkal: false, popular: false, docs: ['Aadhaar Card', 'Address Proof', 'Passport Photo', 'Form 6/7/8'], desc: 'New voter ID card, corrections, or duplicate card application for eligible citizens.' },
  { id: 18, cat: 'personal', name: 'Passport', sub: 'Fresh + Renewal', icon: 'book-open', color: 'blue', time: '3–5 Days', fee: '₹999', tatkal: true,  popular: true,  docs: ['Aadhaar Card', 'Birth Certificate', 'Address Proof', 'Old Passport (renewal)'], desc: 'Passport application for fresh and renewal. Tatkal service for urgent travel.' },
  { id: 19, cat: 'personal', name: 'Driving License', sub: 'New + Renewal', icon: 'car', color: 'orange', time: '3–5 Days', fee: '₹699', tatkal: false, popular: true,  docs: ['Aadhaar Card', 'Learner License', 'Medical Certificate', 'Address Proof'], desc: 'Driving license learner, permanent, renewal and duplicate for all vehicle categories.' },
  { id: 20, cat: 'personal', name: 'Police NOC', sub: 'Verification & NOC', icon: 'shield', color: 'green', time: '7–10 days', fee: '₹299', tatkal: false, popular: false, docs: ['Aadhaar Card', 'Passport Photo', 'Purpose Letter'], desc: 'Police verification NOC for passport, job, tenant, domestic servant verification.' },
  { id: 21, cat: 'personal', name: 'Employment Exchange', sub: 'Registration', icon: 'briefcase', color: 'purple', time: 'Same Day', fee: '₹199', tatkal: false, popular: false, docs: ['Aadhaar', 'Education Certificates', 'Passport Photo'], desc: 'Employment Exchange registration for government job preference and vacancy notifications.' },
  { id: 22, cat: 'personal', name: 'Affidavit Services', sub: 'Multiple Types', icon: 'scroll', color: 'blue', time: 'Instant — 10 min', fee: '₹249', tatkal: false, popular: false, docs: ['Aadhaar Card', 'Relevant Documents', 'Stamp Paper'], desc: 'Notarized affidavits for name change, income declaration, address proof, relationship etc.' },
  { id: 23, cat: 'personal', name: 'Name/DOB Correction', sub: 'In Certificates', icon: 'edit', color: 'orange', time: '5–10 days', fee: '₹349', tatkal: false, popular: false, docs: ['Original Certificate', 'Aadhaar', 'Gazette Notification (name)', 'School Records'], desc: 'Correction of name or date of birth in school/board certificates and government records.' },
  { id: 24, cat: 'personal', name: 'Duplicate Certificate', sub: 'All Types', icon: 'copy', color: 'green', time: '1–2 Days', fee: '₹299', tatkal: false, popular: false, docs: ['FIR Copy', 'Original Application', 'Aadhaar', 'Fee Receipt'], desc: 'Duplicate issuance for lost or damaged government certificates of all types.' },
  { id: 25, cat: 'personal', name: 'Backward Class Certificate', sub: 'BC-I / BC-II', icon: 'users', color: 'blue', time: '1–2 Days', fee: '₹299', tatkal: true,  popular: false, docs: ['Aadhaar', 'Ration Card', 'Caste Proof', 'Passport Photo'], desc: 'Backward Class certificate for Bihar BC-I and BC-II category reservation benefits.' },
  { id: 26, cat: 'personal', name: 'Income & Asset Certificate', sub: 'For EWS', icon: 'file-check', color: 'purple', time: '1–2 Days', fee: '₹349', tatkal: true,  popular: false, docs: ['Aadhaar', 'Income Proof', 'Property Details', 'Annual Return'], desc: 'Combined income and asset certificate required for EWS category applicants.' },
  { id: 27, cat: 'personal', name: 'OBC Certificate', sub: 'State / Central', icon: 'award', color: 'orange', time: '1–2 Days', fee: '₹299', tatkal: true,  popular: false, docs: ['Aadhaar', 'Ration Card', 'Caste Proof', 'Passport Photo'], desc: 'OBC certificate valid for both State and Central government reservations and schemes.' },
  { id: 28, cat: 'personal', name: 'Tatkal Urgent Services', sub: '24–48 Hour Delivery', icon: 'zap', color: 'orange', time: 'Instant — 10 min', fee: '₹699+', tatkal: false, popular: true,  docs: ['All Required Documents', 'Tatkal Fee (extra)'], desc: 'Urgent tatkal processing for income, caste, residence and other certificates in 24–48 hours.' },
  { id: 29, cat: 'personal', name: 'Property Documents', sub: 'Mutation, Dakhil-Kharij', icon: 'building', color: 'blue', time: '2–3 Days', fee: '₹599', tatkal: false, popular: false, docs: ['Aadhaar', 'Sale Deed', 'Khasra Number', 'Mutation Papers'], desc: 'Property mutation, dakhil-kharij, and LPC documentation assistance.' },
  { id: 30, cat: 'personal', name: 'Identity Proof Services', sub: 'Multiple ID Documents', icon: 'id-card', color: 'green', time: '3–7 days', fee: '₹249', tatkal: false, popular: false, docs: ['Existing ID', 'Address Proof'], desc: 'Assistance with various identity proof documents for different government requirements.' },

  // ── ACADEMIC (24) ────────────────────────────────────────────────────────
  { id: 31, cat: 'academic', name: 'College Admission Form', sub: 'University Applications', icon: 'graduation-cap', color: 'blue', time: 'Instant — 10 min', fee: '₹199', tatkal: false, popular: true,  docs: ['10th/12th Marksheet', 'Aadhaar', 'Category Certificate', 'Passport Photo'], desc: 'Form filling assistance for Bihar university and college admissions including OFSS portal.' },
  { id: 32, cat: 'academic', name: 'Government Job Forms', sub: 'BPSC, SSC, Railway, Teacher', icon: 'briefcase', color: 'orange', time: 'Instant — 10 min', fee: '₹299', tatkal: false, popular: true,  docs: ['All Certificates', 'Aadhaar', 'Photo', 'Signature'], desc: 'Government job application for BPSC, SSC CGL/CHSL, Railway RRB and Teacher recruitment.' },
  { id: 33, cat: 'academic', name: 'Board Exam Forms', sub: '10th / 12th Bihar Board', icon: 'book', color: 'green', time: 'Instant — 10 min', fee: '₹199', tatkal: false, popular: true,  docs: ['Admission Card', 'Aadhaar', 'School Certificate', 'Fee Challan'], desc: 'Bihar Board BSEB 10th and 12th examination form filling and verification.' },
  { id: 34, cat: 'academic', name: 'Competitive Exam Forms', sub: 'NEET, JEE, Bihar CET', icon: 'target', color: 'purple', time: 'Instant — 10 min', fee: '₹249', tatkal: false, popular: true,  docs: ['Aadhaar', 'Class 12 Marksheet', 'Category Certificate', 'Photo & Signature'], desc: 'NEET, JEE Main, Bihar CET and other competitive exam form filling with verification.' },
  { id: 35, cat: 'academic', name: 'Scholarship Applications', sub: 'Central + Bihar Scholarships', icon: 'award', color: 'blue', time: '2–3 days', fee: '₹249', tatkal: false, popular: true,  docs: ['Marksheet', 'Income Certificate', 'Caste Certificate', 'Bank Passbook'], desc: 'All central and Bihar state scholarship applications for eligible students.' },
  { id: 36, cat: 'academic', name: 'Bihar Student Credit Card', sub: 'Up to ₹4 Lakh Loan', icon: 'credit-card', color: 'orange', time: 'Same Day', fee: '₹349', tatkal: false, popular: true,  docs: ['12th Marksheet', 'Aadhaar', 'Income Certificate', 'Admission Letter'], desc: 'Bihar Student Credit Card scheme for ₹4 lakh loan at 0% interest for girls and 1% for others.' },
  { id: 37, cat: 'academic', name: 'Hostel Assistance', sub: 'Admission & Fees', icon: 'building-2', color: 'green', time: '2–3 days', fee: '₹199', tatkal: false, popular: false, docs: ['Caste Certificate', 'Income Certificate', 'Marksheet', 'Aadhaar'], desc: 'Government hostel admission form and fee assistance for SC/ST/OBC students.' },
  { id: 38, cat: 'academic', name: 'Migration / TC', sub: 'Transfer Certificate', icon: 'move-right', color: 'purple', time: 'Same Day', fee: '₹199', tatkal: false, popular: false, docs: ['Previous Institute Certificate', 'Aadhaar', 'Application'], desc: 'Migration certificate and transfer certificate from school or college.' },
  { id: 39, cat: 'academic', name: 'Degree Verification', sub: 'Certificate Authentication', icon: 'badge-check', color: 'blue', time: '1–2 Days', fee: '₹299', tatkal: false, popular: false, docs: ['Original Degree', 'Aadhaar', 'Fee', 'Application Form'], desc: 'University degree and diploma certificate verification from Bihar universities.' },
  { id: 40, cat: 'academic', name: 'Education Loan Help', sub: 'Bank Loan Assistance', icon: 'banknote', color: 'orange', time: 'Same Day', fee: '₹299', tatkal: false, popular: false, docs: ['Admission Letter', 'Marksheets', 'Income Certificate', 'Guarantor Documents'], desc: 'Education loan application assistance from nationalized banks.' },
  { id: 41, cat: 'academic', name: 'Skill Development', sub: 'PMKVY Registration', icon: 'wrench', color: 'green', time: 'Instant — 10 min', fee: '₹149', tatkal: false, popular: false, docs: ['Aadhaar', 'Education Certificate', 'Bank Account'], desc: 'PMKVY and Bihar Skill Development scheme registration for free vocational training.' },
  { id: 42, cat: 'academic', name: 'RTE Admission', sub: 'Right to Education', icon: 'school', color: 'purple', time: '2–3 days', fee: '₹199', tatkal: false, popular: false, docs: ['Birth Certificate', 'Aadhaar', 'Income Certificate', 'Address Proof'], desc: 'RTE Act 25% reservation admission in private schools for BPL children.' },
  { id: 43, cat: 'academic', name: 'Girl Child Scholarships', sub: 'Balika Schemes', icon: 'star', color: 'blue', time: '2–3 days', fee: '₹249', tatkal: false, popular: true,  docs: ['Marksheet', 'Aadhaar', 'Income Certificate', 'Bank Passbook'], desc: 'Mukhyamantri Balika Cycle, Poshak Yojana and other girl-specific scholarship benefits.' },
  { id: 44, cat: 'academic', name: 'Merit / Means Scholarships', sub: 'All Categories', icon: 'trophy', color: 'orange', time: '2–3 days', fee: '₹249', tatkal: false, popular: false, docs: ['Marksheet', 'Income Certificate', 'Aadhaar', 'Bank Account'], desc: 'Merit and means-based scholarship applications for outstanding students in need.' },
  { id: 45, cat: 'academic', name: 'PhD / Fellowship', sub: 'Higher Education Funding', icon: 'flask-conical', color: 'green', time: 'Same Day', fee: '₹349', tatkal: false, popular: false, docs: ['PG Degree', 'Research Proposal', 'NET/JRF Score', 'Aadhaar'], desc: 'PhD fellowship and higher education research scholarship applications.' },
  { id: 46, cat: 'academic', name: 'Vocational Courses', sub: 'ITI & Polytechnic', icon: 'settings', color: 'purple', time: 'Instant — 10 min', fee: '₹149', tatkal: false, popular: false, docs: ['Education Certificate', 'Aadhaar', 'Income Certificate'], desc: 'Vocational and technical course admission in ITI and polytechnic colleges.' },
  { id: 47, cat: 'academic', name: 'Sports Scholarships', sub: 'Athletic Excellence', icon: 'medal', color: 'blue', time: '2–3 days', fee: '₹199', tatkal: false, popular: false, docs: ['Achievement Certificate', 'School Certificate', 'Aadhaar'], desc: 'Sports and cultural activity scholarships for Bihar students.' },
  { id: 48, cat: 'academic', name: 'Exam Re-evaluation', sub: 'Marks Verification', icon: 'search', color: 'orange', time: '2–3 days', fee: '₹299', tatkal: false, popular: false, docs: ['Marksheet', 'Application', 'Re-evaluation Fee Challan'], desc: 'Bihar Board examination re-evaluation and scrutiny form filling assistance.' },
  { id: 49, cat: 'academic', name: 'University Registration', sub: 'Enrollment Form', icon: 'clipboard-list', color: 'green', time: 'Instant — 10 min', fee: '₹199', tatkal: false, popular: false, docs: ['12th Marksheet', 'Aadhaar', 'Admission Letter', 'Photo'], desc: 'University registration and enrollment form filling for new students.' },
  { id: 50, cat: 'academic', name: 'Mukhyamantri Kanya Utthan', sub: 'Education Incentive', icon: 'heart-handshake', color: 'purple', time: '2–3 days', fee: '₹249', tatkal: false, popular: true,  docs: ['Graduation Marksheet', 'Aadhaar', 'Bank Account', 'Income Certificate'], desc: 'Mukhyamantri Kanya Utthan Yojana graduation incentive ₹50,000 application for Bihar girls.' },
  { id: 51, cat: 'academic', name: 'Post-Matric Scholarship', sub: 'Class 11 and Above', icon: 'book-open', color: 'blue', time: '2–3 days', fee: '₹249', tatkal: false, popular: false, docs: ['10th Marksheet', 'Income Certificate', 'Caste Certificate', 'Bank Account'], desc: 'Central and Bihar post-matric scholarship for SC/ST/OBC/Minority students.' },
  { id: 52, cat: 'academic', name: 'Pre-Matric Scholarship', sub: 'Class 1–10', icon: 'pencil', color: 'orange', time: '2–3 days', fee: '₹199', tatkal: false, popular: false, docs: ['Marksheet', 'Aadhaar', 'Income Certificate', 'Caste Certificate'], desc: 'Pre-matric scholarship for minority and SC students in classes 1 to 10.' },
  { id: 53, cat: 'academic', name: 'Technical Scholarships', sub: 'Engineering / Medical', icon: 'cpu', color: 'green', time: '2–3 days', fee: '₹299', tatkal: false, popular: false, docs: ['JEE/NEET Score', 'Admission Letter', 'Caste Certificate', 'Bank Account'], desc: 'Technical education scholarships for engineering and medical students in Bihar.' },
  { id: 54, cat: 'academic', name: 'Overseas Scholarship', sub: 'Foreign Study Assistance', icon: 'plane', color: 'purple', time: '1–2 Days', fee: '₹499', tatkal: false, popular: false, docs: ['Passport', 'Admission Letter', 'Academic Records', 'Income Certificate'], desc: 'Bihar and central government overseas scholarship for higher studies abroad.' },

  // ── BUSINESS (20) ────────────────────────────────────────────────────────
  { id: 55, cat: 'business', name: 'GST Registration', sub: 'New + Return Filing', icon: 'receipt', color: 'blue', time: 'Same Day', fee: '₹999', tatkal: false, popular: true,  docs: ['PAN Card', 'Aadhaar', 'Business Address Proof', 'Bank Statement'], desc: 'GST registration for new businesses and regular/quarterly return filing assistance.' },
  { id: 56, cat: 'business', name: 'ITR Filing', sub: 'All Types – Salaried / Business', icon: 'file-spreadsheet', color: 'orange', time: '1–3 days', fee: '₹499', tatkal: false, popular: true,  docs: ['PAN', 'Aadhaar', 'Form 16 / Salary Slip', 'Bank Statement'], desc: 'Income Tax Return filing for individuals, salaried, business and professionals.' },
  { id: 57, cat: 'business', name: 'Udyam MSME Registration', sub: 'New + Update', icon: 'factory', color: 'green', time: 'Instant — 10 min', fee: '₹499', tatkal: false, popular: true,  docs: ['PAN Card', 'Aadhaar', 'Business Details', 'Bank Account'], desc: 'Udyam MSME registration for micro, small and medium enterprises for government benefits.' },
  { id: 58, cat: 'business', name: 'Shop & Establishment', sub: 'New + Renewal License', icon: 'store', color: 'purple', time: '1–2 Days', fee: '₹699', tatkal: false, popular: false, docs: ['Aadhaar', 'Business Address', 'Rent Agreement', 'Passport Photo'], desc: 'Shop and establishment license from Bihar Municipal Corporation or BDO office.' },
  { id: 59, cat: 'business', name: 'FSSAI License', sub: 'Food Business License', icon: 'utensils', color: 'blue', time: '2–3 Days', fee: '₹899', tatkal: false, popular: true,  docs: ['PAN', 'Aadhaar', 'Food Business Details', 'Address Proof'], desc: 'FSSAI food safety registration and license for restaurants, food manufacturers and traders.' },
  { id: 60, cat: 'business', name: 'Trade License', sub: 'Local Body License', icon: 'briefcase', color: 'orange', time: '5–10 days', fee: '₹699', tatkal: false, popular: false, docs: ['Aadhaar', 'Business Address', 'Rent Agreement', 'NOC'], desc: 'Trade license from Patna Municipal Corporation for commercial establishments.' },
  { id: 61, cat: 'business', name: 'Professional Tax', sub: 'Registration', icon: 'landmark', color: 'green', time: 'Same Day', fee: '₹599', tatkal: false, popular: false, docs: ['PAN', 'Aadhaar', 'Business Certificate', 'Bank Account'], desc: 'Professional tax registration for businesses employing staff in Bihar.' },
  { id: 62, cat: 'business', name: 'EPF & ESIC Registration', sub: 'Employee Benefits', icon: 'users', color: 'purple', time: '1–2 Days', fee: '₹999', tatkal: false, popular: false, docs: ['PAN', 'Aadhaar', 'Business Certificate', 'Employee Details'], desc: 'EPF and ESIC registration for businesses with 10 or more employees.' },
  { id: 63, cat: 'business', name: 'Trademark Registration', sub: 'Brand Protection', icon: 'tag', color: 'blue', time: '30–45 days', fee: '₹2,999', tatkal: false, popular: false, docs: ['Brand Name / Logo', 'PAN', 'Business Certificate', 'Classification'], desc: 'Trademark registration to protect your brand name and logo legally.' },
  { id: 64, cat: 'business', name: 'Import Export Code', sub: 'IEC Registration', icon: 'globe', color: 'orange', time: 'Same Day', fee: '₹1,499', tatkal: false, popular: false, docs: ['PAN', 'Aadhaar', 'Bank Account', 'Business Certificate'], desc: 'IEC registration from DGFT for starting import/export business.' },
  { id: 65, cat: 'business', name: 'TDS Return Filing', sub: 'Quarterly Returns', icon: 'calculator', color: 'green', time: 'Instant — 10 min', fee: '₹699', tatkal: false, popular: false, docs: ['TAN', 'PAN', 'Deductee Details', 'Challan Details'], desc: 'TDS return filing for employers deducting TDS on salaries and other payments.' },
  { id: 66, cat: 'business', name: 'Company Registration', sub: 'Pvt Ltd / LLP / OPC', icon: 'building-2', color: 'purple', time: '7–10 days', fee: '₹2,999', tatkal: false, popular: true,  docs: ['PAN/Aadhaar Directors', 'Business Address', 'MOA/AOA Draft'], desc: 'Company, LLP and OPC registration with Ministry of Corporate Affairs.' },
  { id: 67, cat: 'business', name: 'Partnership Firm', sub: 'Registration', icon: 'handshake', color: 'blue', time: '7–10 days', fee: '₹1,499', tatkal: false, popular: false, docs: ["Partners' PAN/Aadhaar", 'Partnership Deed', 'Business Address', 'Stamp Paper'], desc: 'Partnership firm registration under Bihar Partnership Act.' },
  { id: 68, cat: 'business', name: 'Digital Signature (DSC)', sub: 'Class 2 / Class 3', icon: 'key-round', color: 'orange', time: 'Instant — 10 min', fee: '₹999', tatkal: false, popular: true,  docs: ['PAN', 'Aadhaar', 'Passport Photo', 'Email & Mobile'], desc: 'Digital Signature Certificate for tender filing, MCA portal and income tax.' },
  { id: 69, cat: 'business', name: 'Annual ROC Filing', sub: 'Company Compliance', icon: 'calendar-check', color: 'green', time: 'Same Day', fee: '₹1,499', tatkal: false, popular: false, docs: ['Company CIN', 'Balance Sheet', 'P&L Statement', 'Board Resolution'], desc: 'Annual ROC filing AOC-4 and MGT-7 for registered companies.' },
  { id: 70, cat: 'business', name: 'Labour License', sub: 'Contract Labour', icon: 'hard-hat', color: 'purple', time: '2–3 Days', fee: '₹1,299', tatkal: false, popular: false, docs: ['Establishment Certificate', 'Contract Details', 'PAN', 'Aadhaar'], desc: 'Labour license under Contract Labour Act for construction and manufacturing.' },
  { id: 71, cat: 'business', name: 'ISO Certification', sub: 'Quality Management', icon: 'award', color: 'blue', time: '30–60 days', fee: '₹4,999', tatkal: false, popular: false, docs: ['Business Registration', 'Quality Manual', 'Process Documentation'], desc: 'ISO 9001 and other quality management system certification assistance.' },
  { id: 72, cat: 'business', name: 'Sole Proprietorship', sub: 'Business Setup', icon: 'user', color: 'orange', time: 'Same Day', fee: '₹999', tatkal: false, popular: false, docs: ['Aadhaar', 'PAN', 'Bank Account', 'Business Address'], desc: 'Sole proprietorship setup with GST, Udyam and local authority registrations.' },
  { id: 73, cat: 'business', name: 'GST Annual Return', sub: 'GSTR-9', icon: 'clipboard-list', color: 'green', time: 'Same Day', fee: '₹899', tatkal: false, popular: false, docs: ['GSTIN', 'All Monthly Returns', 'Purchase & Sales Data'], desc: 'GSTR-9 annual return filing for GST registered businesses.' },
  { id: 74, cat: 'business', name: 'Mudra Loan Assistance', sub: 'Up to ₹10 Lakh', icon: 'banknote', color: 'purple', time: '2–3 Days', fee: '₹499', tatkal: false, popular: true,  docs: ['Aadhaar', 'PAN', 'Business Plan', 'Bank Statement', 'Udyam Certificate'], desc: 'PM Mudra Loan for Shishu (₹50K), Kishor (₹5L) and Tarun (₹10L) categories.' },

  // ── CENTRAL SCHEMES (17) ─────────────────────────────────────────────────
  { id: 75,  cat: 'schemes-central', name: 'PM Kisan Samman Nidhi', sub: '₹6,000 Annual Benefit', icon: 'wheat', color: 'green', time: '2–3 Days', fee: '₹249', tatkal: false, popular: true,  docs: ['Aadhaar', 'Khasra / Land Records', 'Bank Account', 'Mobile Number'], desc: 'PM Kisan registration for ₹6,000 annual benefit in 3 instalments for small and marginal farmers.' },
  { id: 76,  cat: 'schemes-central', name: 'Ayushman Bharat PM-JAY', sub: '₹5 Lakh Health Cover', icon: 'heart-pulse', color: 'blue', time: '3–7 days', fee: '₹249', tatkal: false, popular: true,  docs: ['Ration Card', 'Aadhaar', 'SECC Data Verification'], desc: 'PM-JAY health insurance of ₹5 lakh per family per year for 50 crore beneficiaries.' },
  { id: 77,  cat: 'schemes-central', name: 'PM Awas Yojana', sub: 'Housing for All', icon: 'home', color: 'orange', time: '3–5 Days', fee: '₹349', tatkal: false, popular: true,  docs: ['Aadhaar', 'Income Certificate', 'Land Proof', 'Bank Account'], desc: 'PMAY housing scheme for rural and urban poor families. Subsidy up to ₹2.67 lakh.' },
  { id: 78,  cat: 'schemes-central', name: 'PM Ujjwala Yojana', sub: 'Free LPG Connection', icon: 'flame', color: 'orange', time: '2–3 Days', fee: '₹199', tatkal: false, popular: true,  docs: ['Aadhaar', 'BPL / Ration Card', 'Bank Account', 'Address Proof'], desc: 'Free LPG connection for BPL women under PM Ujjwala Yojana 2.0.' },
  { id: 79,  cat: 'schemes-central', name: 'PM Mudra Yojana', sub: 'Business Loan Upto ₹10L', icon: 'banknote', color: 'green', time: '2–3 Days', fee: '₹299', tatkal: false, popular: false, docs: ['Aadhaar', 'PAN', 'Business Details', 'Bank Statement'], desc: 'PM Mudra collateral-free business loan up to ₹10 lakh under Shishu, Kishor, Tarun.' },
  { id: 80,  cat: 'schemes-central', name: 'PM Fasal Bima Yojana', sub: 'Crop Insurance', icon: 'leaf', color: 'green', time: '3–7 days', fee: '₹199', tatkal: false, popular: false, docs: ['Aadhaar', 'Land Records', 'Bank Account', 'Crop Sowing Details'], desc: 'PM Fasal Bima Yojana crop insurance for farmers against natural calamities.' },
  { id: 81,  cat: 'schemes-central', name: 'PM Matru Vandana', sub: '₹5,000 for First Birth', icon: 'baby', color: 'purple', time: '5–10 days', fee: '₹199', tatkal: false, popular: false, docs: ['Aadhaar', 'MCP Card', 'Bank Account', 'Marriage Certificate'], desc: 'Maternity benefit of ₹5,000 for first live birth under Pradhan Mantri Matru Vandana Yojana.' },
  { id: 82,  cat: 'schemes-central', name: 'Atal Pension Yojana', sub: 'Guaranteed Pension Scheme', icon: 'calendar', color: 'blue', time: 'Same Day', fee: '₹199', tatkal: false, popular: false, docs: ['Aadhaar', 'Bank Account', 'Mobile Number'], desc: 'Guaranteed pension of ₹1,000–₹5,000 per month after age 60 under Atal Pension Yojana.' },
  { id: 83,  cat: 'schemes-central', name: 'PM Jeevan Jyoti Bima', sub: '₹2 Lakh Life Cover', icon: 'shield', color: 'green', time: 'Instant — 10 min', fee: '₹149', tatkal: false, popular: false, docs: ['Aadhaar', 'Bank Account', 'Nominee Details'], desc: 'Life insurance of ₹2 lakh at just ₹436 per year for age 18–50 under PMJJBY.' },
  { id: 84,  cat: 'schemes-central', name: 'PM Suraksha Bima', sub: '₹2 Lakh Accident Cover', icon: 'shield-check', color: 'orange', time: 'Instant — 10 min', fee: '₹99', tatkal: false, popular: false, docs: ['Aadhaar', 'Bank Account', 'Nominee Details'], desc: 'Accident insurance of ₹2 lakh at only ₹20 per year under PM Suraksha Bima Yojana.' },
  { id: 85,  cat: 'schemes-central', name: 'Stand Up India', sub: 'SC/ST/Women Loan', icon: 'trending-up', color: 'purple', time: '3–5 Days', fee: '₹499', tatkal: false, popular: false, docs: ['Aadhaar', 'PAN', 'Business Plan', 'Caste Certificate'], desc: 'Bank loan ₹10 lakh to ₹1 crore for SC/ST and women entrepreneurs under Stand Up India.' },
  { id: 86,  cat: 'schemes-central', name: 'MGNREGA Job Card', sub: '100 Days Employment', icon: 'shovel', color: 'green', time: '5–10 days', fee: '₹199', tatkal: false, popular: true,  docs: ['Aadhaar', 'Ration Card', 'Passport Photo', 'Bank Account'], desc: 'MGNREGA job card for guaranteed 100 days employment per year for rural families.' },
  { id: 87,  cat: 'schemes-central', name: 'Jal Jeevan Mission', sub: 'Har Ghar Nal', icon: 'droplets', color: 'blue', time: '2–3 Days', fee: '₹199', tatkal: false, popular: false, docs: ['Aadhaar', 'House Proof', 'Application Form'], desc: 'Jal Jeevan Mission application for piped water supply to every household.' },
  { id: 88,  cat: 'schemes-central', name: 'Swachh Bharat Mission', sub: 'Toilet Construction Grant', icon: 'building', color: 'orange', time: '2–3 Days', fee: '₹199', tatkal: false, popular: false, docs: ['Aadhaar', 'BPL Card', 'Land Proof', 'Bank Account'], desc: 'SBM application for toilet construction grant under Swachh Bharat Mission (Gramin).' },
  { id: 89,  cat: 'schemes-central', name: 'Beti Bachao Beti Padhao', sub: 'Girl Child Scheme', icon: 'heart', color: 'purple', time: 'Same Day', fee: '₹199', tatkal: false, popular: false, docs: ['Birth Certificate (Girl)', "Parents' Aadhaar", 'Bank Account'], desc: 'BBBP scheme for welfare, education and protection of girl child in India.' },
  { id: 90,  cat: 'schemes-central', name: 'PM Garib Kalyan Anna', sub: 'Free Ration Scheme', icon: 'package', color: 'green', time: '5–10 days', fee: '₹199', tatkal: false, popular: false, docs: ['Ration Card', 'Aadhaar', 'NFSA Registration'], desc: 'PM Garib Kalyan Anna Yojana registration for free foodgrains under National Food Security Act.' },
  { id: 91,  cat: 'schemes-central', name: 'PM Surya Ghar Yojana', sub: 'Free Solar Electricity', icon: 'sun', color: 'orange', time: '3–5 Days', fee: '₹349', tatkal: false, popular: true,  docs: ['Aadhaar', 'Electricity Bill', 'House Ownership Proof', 'Bank Account'], desc: 'PM Surya Ghar Muft Bijli Yojana for rooftop solar installation with subsidy up to ₹78,000.' },

  // ── BIHAR STATE SCHEMES (17) ─────────────────────────────────────────────
  { id: 92,  cat: 'schemes-bihar', name: 'Bihar Student Credit Card', sub: '₹4 Lakh Education Loan', icon: 'credit-card', color: 'blue', time: 'Same Day', fee: '₹349', tatkal: false, popular: true,  docs: ['12th Marksheet', 'Aadhaar', 'Income Certificate', 'Admission Letter'], desc: 'Bihar Student Credit Card scheme for ₹4 lakh education loan at 0% for girls, 1% for others.' },
  { id: 93,  cat: 'schemes-bihar', name: 'Mukhyamantri Kanya Utthan', sub: 'Graduation Incentive ₹50K', icon: 'graduation-cap', color: 'orange', time: '2–3 days', fee: '₹249', tatkal: false, popular: true,  docs: ['Graduation Marksheet', 'Aadhaar', 'Bank Account', 'Income Certificate'], desc: '₹50,000 incentive for unmarried girls on graduation under Mukhyamantri Kanya Utthan Yojana.' },
  { id: 94,  cat: 'schemes-bihar', name: 'Balika Cycle Yojana', sub: 'Free Cycle for Class 9 Girls', icon: 'bike', color: 'green', time: '2–3 days', fee: '₹149', tatkal: false, popular: false, docs: ['School ID', 'Aadhaar', 'Income Certificate', 'Application Form'], desc: 'Free bicycle for girls enrolled in class 9 under Mukhyamantri Balika Cycle Yojana.' },
  { id: 95,  cat: 'schemes-bihar', name: 'Balika Poshak Yojana', sub: 'Uniform Allowance', icon: 'shirt', color: 'purple', time: '2–3 days', fee: '₹149', tatkal: false, popular: false, docs: ['School ID', 'Aadhaar', 'Application Form'], desc: 'Uniform allowance ₹600–₹1,500 for girls in class 1–12 under Balika Poshak Yojana.' },
  { id: 96,  cat: 'schemes-bihar', name: 'Vridhajan Pension', sub: 'Old Age Pension', icon: 'user-check', color: 'blue', time: '2–3 Days', fee: '₹249', tatkal: false, popular: true,  docs: ['Aadhaar', 'Age Proof', 'Bank Account', 'BPL Certificate'], desc: 'Old age pension ₹400–₹500 per month for BPL senior citizens above 60 in Bihar.' },
  { id: 97,  cat: 'schemes-bihar', name: 'Divyang Pension', sub: 'Disability Pension', icon: 'accessibility', color: 'orange', time: '2–3 Days', fee: '₹249', tatkal: false, popular: false, docs: ['Aadhaar', 'Disability Certificate', 'Bank Account', 'Income Certificate'], desc: 'Monthly pension for persons with 40%+ disability under Bihar Divyang Pension Yojana.' },
  { id: 98,  cat: 'schemes-bihar', name: 'Mahila Udyami Yojana', sub: 'Women Entrepreneur Loan ₹10L', icon: 'store', color: 'green', time: '3–5 Days', fee: '₹499', tatkal: false, popular: true,  docs: ['Aadhaar', 'PAN', 'Business Plan', 'Income Certificate'], desc: 'Mukhyamantri Mahila Udyami Yojana for ₹10 lakh loan at 0% interest for women entrepreneurs.' },
  { id: 99,  cat: 'schemes-bihar', name: '7 Nischay Schemes', sub: 'Multiple Development Schemes', icon: 'layers', color: 'purple', time: '2–3 Days', fee: '₹299', tatkal: false, popular: false, docs: ['Aadhaar', 'Category Certificate', 'Income Certificate'], desc: 'Bihar 7 Nischay – Aarthik Hal Yuvaon Ka Bal, Ghar Tak Pakki Gali and other development schemes.' },
  { id: 100, cat: 'schemes-bihar', name: 'Fasal Sahayata Yojana', sub: 'Crop Damage Compensation', icon: 'wheat', color: 'blue', time: '2–3 Days', fee: '₹249', tatkal: false, popular: false, docs: ['Aadhaar', 'Land Records', 'Bank Account', 'Kisan Registration'], desc: 'Bihar Rajya Fasal Sahayata Yojana compensation for flood or drought-related crop damage.' },
  { id: 101, cat: 'schemes-bihar', name: 'Girl Graduation Incentive', sub: 'CM Girls Scheme', icon: 'award', color: 'orange', time: '2–3 days', fee: '₹249', tatkal: false, popular: true,  docs: ['Graduation Certificate', 'Aadhaar', 'Bank Account', 'Marital Status Proof'], desc: 'Chief Minister Girls Graduation Incentive for unmarried women graduates in Bihar.' },
  { id: 102, cat: 'schemes-bihar', name: 'Nari Shakti Yojana', sub: 'Women Empowerment', icon: 'users', color: 'green', time: '5–10 days', fee: '₹249', tatkal: false, popular: false, docs: ['Aadhaar', 'Income Certificate', 'Bank Account'], desc: 'Nari Shakti and Sambal scheme for women empowerment and social security in Bihar.' },
  { id: 103, cat: 'schemes-bihar', name: 'DBT Direct Transfer', sub: 'All DBT Scheme Linking', icon: 'arrow-right-circle', color: 'purple', time: '3–7 days', fee: '₹199', tatkal: false, popular: false, docs: ['Aadhaar', 'Bank Account', 'Scheme Eligibility Proof'], desc: 'DBT registration and Aadhaar-bank seeding for all direct benefit transfer schemes.' },
  { id: 104, cat: 'schemes-bihar', name: 'Widow Pension', sub: 'Vidhwa Pension Yojana', icon: 'heart-handshake', color: 'blue', time: '2–3 Days', fee: '₹249', tatkal: false, popular: false, docs: ['Aadhaar', "Husband's Death Certificate", 'Income Proof', 'Bank Account'], desc: 'Monthly pension for BPL widows under Bihar Widow Pension (Indira Gandhi National Widow Pension).' },
  { id: 105, cat: 'schemes-bihar', name: 'Har Ghar Bijli', sub: 'Free Electricity Connection', icon: 'zap', color: 'orange', time: '2–3 Days', fee: '₹249', tatkal: false, popular: false, docs: ['Aadhaar', 'House Proof', 'Application Form'], desc: 'Har Ghar Bijli Lagatar scheme for free electricity connection to every household in Bihar.' },
  { id: 106, cat: 'schemes-bihar', name: 'Kushal Yuva Program', sub: 'Skill & Communication Training', icon: 'wrench', color: 'green', time: 'Same Day', fee: '₹199', tatkal: false, popular: false, docs: ['Aadhaar', '10th Certificate', 'Age Proof', 'Bank Account'], desc: 'Kushal Yuva Program for skill development and English/IT communication training for Bihar youth.' },
  { id: 107, cat: 'schemes-bihar', name: 'Gram Parivahan Yojana', sub: 'Vehicle Purchase Subsidy', icon: 'truck', color: 'purple', time: '3–5 Days', fee: '₹349', tatkal: false, popular: false, docs: ['Aadhaar', 'Caste Certificate', 'Driving License', 'Bank Account'], desc: 'Mukhyamantri Gram Parivahan Yojana subsidy of ₹1 lakh for SC/ST/EBC for commercial vehicles.' },
  { id: 108, cat: 'schemes-bihar', name: 'Jeevika / SHG Scheme', sub: 'Self Help Group', icon: 'users', color: 'blue', time: '5–10 days', fee: '₹249', tatkal: false, popular: false, docs: ['Aadhaar', 'Bank Account', 'Group Formation Documents'], desc: 'Jeevika Bihar SHG registration and livelihood scheme benefits for rural women.' },
];

export const colorMap: Record<IconColor, { bg: string; icon: string }> = {
  blue:   { bg: '#E8EEF8', icon: '#003087' },
  orange: { bg: '#FFF3E6', icon: '#FF9933' },
  green:  { bg: '#ECFDF5', icon: '#059669' },
  purple: { bg: '#F5F3FF', icon: '#7C3AED' },
  rose:   { bg: '#FFF1F2', icon: '#E11D48' },
};

export const categoryMeta = {
  personal:        { label: 'Personal Documents', count: 30 },
  academic:        { label: 'Academic & Education', count: 24 },
  business:        { label: 'Business Services', count: 20 },
  'schemes-central': { label: 'Central Schemes', count: 17 },
  'schemes-bihar': { label: 'Bihar State Schemes', count: 17 },
};
